/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ActionButton {
    'disabled': boolean;
  }
  interface CounterBox {
    'max': number;
    'min': number;
    'start': number;
  }
  interface HelloWorld {
    'first': string;
    'last': string;
    'middle': string;
  }
}

declare global {


  interface HTMLActionButtonElement extends Components.ActionButton, HTMLStencilElement {}
  var HTMLActionButtonElement: {
    prototype: HTMLActionButtonElement;
    new (): HTMLActionButtonElement;
  };

  interface HTMLCounterBoxElement extends Components.CounterBox, HTMLStencilElement {}
  var HTMLCounterBoxElement: {
    prototype: HTMLCounterBoxElement;
    new (): HTMLCounterBoxElement;
  };

  interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {}
  var HTMLHelloWorldElement: {
    prototype: HTMLHelloWorldElement;
    new (): HTMLHelloWorldElement;
  };
  interface HTMLElementTagNameMap {
    'action-button': HTMLActionButtonElement;
    'counter-box': HTMLCounterBoxElement;
    'hello-world': HTMLHelloWorldElement;
  }
}

declare namespace LocalJSX {
  interface ActionButton extends JSXBase.HTMLAttributes<HTMLActionButtonElement> {
    'disabled'?: boolean;
  }
  interface CounterBox extends JSXBase.HTMLAttributes<HTMLCounterBoxElement> {
    'max'?: number;
    'min'?: number;
    'start'?: number;
  }
  interface HelloWorld extends JSXBase.HTMLAttributes<HTMLHelloWorldElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface IntrinsicElements {
    'action-button': ActionButton;
    'counter-box': CounterBox;
    'hello-world': HelloWorld;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


